### ISSUE TITLE
Inchling can't break some blocks

### ISSUE THREAD

**Issue by CSUMBRACCOONLORD** [0vergrown/Improved-Inchling-Origin#1]
Hey there! 

First I wanted to thank you for making this origin! I think it's super cool that someone put into effort to make this! That said, I've been encountering a very strange issue. Basically while the inchling can break most blocks albeit much slower, for whatever reason, they can't break things like flowers and sugarcane. Not even standing in front of it and punching it for a really long time does anything. I have no idea why this might be the case, but if I can't even clear some grass out of the way, that's gonna prove to be a bit of a problem. I'd really appreciate if you could look into this issue because I'm not convinced that it's intended. Anyway, 

I hope you're having a good day so far!

**Comment by 0vergrown** [comment]
Resolved an issue with the "Slow Miner" power that didn't allow users to break certain blocks such as grass, flowers, crops, and sugar cane. This fix involves the addition of all breakable blocks to a JSON tag file, thereby fixing the unbreakable block issue as of version 2.0.2

https://modrinth.com/datapack/improved-inchling-origin/version/2.0.2
