### ISSUE TITLE
cannot eat sugar

### ISSUE THREAD

**Issue by C00414139-ULL** [0vergrown/Improved-Inchling-Origin#3]
hello, i am using the mod version 2.1.0 of this on forge 47.2.18. 
upon updating to the new version of the mod that addresses issue#2. I have found that I am unable to consume sugar at all.
upon searching through the datapack version under powers/sugar_fueled_frenzy.json, i notice this

"item_condition":{
         "type":"origins:ingredient",
         "ingredient":{
            "item":"minecraft:sugar"
         }
      }

this section defines the item to be consumed for the sugar_fueled_frenzy power, by what i can only assume is a tag being checked on the item minecraft:sugar based on this statement. 

looking further, i unpacked the improved-inchling-origin-2.0.3.jar that i was using prior to this update. looking through the powers/sugar_fueled_frenzy.json, I noticed how the sugar was being consumed had completely changed. for v2.1.0 you used

"eat":{
      "type":"origins:edible_item",
      "entity_action":{...},
      "item_condition":{
         "type":"origins:ingredient",
         "ingredient":{
            "item":"minecraft:sugar"
         }
      },
      "food_component":{...},
      "consume_action":"eat",
      ...
}

but for v2.0.3, the means of eating sugar was

"active": {
        "type": "origins:active_self",
        "entity_action": {
            "type": "origins:and",
            "actions": [
                {
                    "type": "origins:equipped_item_action",
                    "equipment_slot": "mainhand",
                    "action": {
                        "type": "origins:consume",
                        "amount": 1
                    }
                    ...
}

so an item action of type consume was used before to eat sugar, but now its an entity action of "change_resource" with a condition of minecraft:sugar and the consume action "eat"

I'm sorry to pry and throw your own code at you, but i believe this to be the root of this issue. I'm unsure why it does not work, as both seem to be a method of consuming a specified item (minecraft:sugar) on a right click to change the resource "improved_inchling:sugar_fueled_frenzy_consume_resource", and both seems like they should work given the documentation i was able to search for on both. [ https://origins.readthedocs.io/en/latest/types/item_action_types/consume/ , https://origins.readthedocs.io/en/latest/types/entity_action_types/change_resource/ ]

**Comment by 0vergrown** [comment]
> hello, i am using the mod version 2.1.0 of this on forge 47.2.18. 
> upon updating to the new version of the mod that addresses issue#2. I have found that I am unable to consume sugar at all.
> upon searching through the datapack version under powers/sugar_fueled_frenzy.json, i notice this
> 
> "item_condition":{
>          "type":"origins:ingredient",
>          "ingredient":{
>             "item":"minecraft:sugar"
>          }
>       }
> 
> this section defines the item to be consumed for the sugar_fueled_frenzy power, by what i can only assume is a tag being checked on the item minecraft:sugar based on this statement. 
> 
> looking further, i unpacked the improved-inchling-origin-2.0.3.jar that i was using prior to this update. looking through the powers/sugar_fueled_frenzy.json, I noticed how the sugar was being consumed had completely changed. for v2.1.0 you used
> 
> "eat":{
>       "type":"origins:edible_item",
>       "entity_action":{...},
>       "item_condition":{
>          "type":"origins:ingredient",
>          "ingredient":{
>             "item":"minecraft:sugar"
>          }
>       },
>       "food_component":{...},
>       "consume_action":"eat",
>       ...
> }
> 
> but for v2.0.3, the means of eating sugar was
> 
> "active": {
>         "type": "origins:active_self",
>         "entity_action": {
>             "type": "origins:and",
>             "actions": [
>                 {
>                     "type": "origins:equipped_item_action",
>                     "equipment_slot": "mainhand",
>                     "action": {
>                         "type": "origins:consume",
>                         "amount": 1
>                     }
>                     ...
> }
> 
> 
> 
> so an item action of type consume was used before to eat sugar, but now its an entity action of "change_resource" with a condition of minecraft:sugar and the consume action "eat"
> 
> I'm sorry to pry and throw your own code at you, but i believe this to be the root of this issue. I'm unsure why it does not work, as both seem to be a method of consuming a specified item (minecraft:sugar) on a right click to change the resource "improved_inchling:sugar_fueled_frenzy_consume_resource", and both seems like they should work given the documentation i was able to search for on both. [ https://origins.readthedocs.io/en/latest/types/item_action_types/consume/ , https://origins.readthedocs.io/en/latest/types/entity_action_types/change_resource/ ]

Forge is currently outdated in datapack features. It should only affect you if you want to use custom datapack origins from the newer versions. I did upload a new update that uses Apugli as a dependency that fixes the eating issue.

https://modrinth.com/datapack/improved-inchling-origin/versions

**Comment by C00414139-ULL** [comment]
thanks for taking the time for the fix. sorry for bugging you with 2 issues, but you have a great day.
