### ISSUE TITLE
Inchling can't interact with certain pets

### ISSUE THREAD

**Issue by jocoserious95** [0vergrown/Improved-Inchling-Origin#4]
Using this mod in a modpack with other mods that require an empty hand to interact with pets, I can't make the pets sit because it just makes me ride them. My friend updated to include the 'mount shift+right click' fix, but that just makes me instantly dismount. Help? I'd like to be able to interact with pets _and_ ride things.

**Comment by 0vergrown** [comment]
Bug has been fixed in the latest version of the Origin; changes will be uploaded later today to the Modrinth page, but the changes are currently available here in the GitHub
